title: Kalpan Tumdi # your name (or website title) here
logo: "/images/Kalpan_Tumdi_Photo.png" # your photo (or logo) here
description: >+ # your text below (remove <br> elements if you don't need line breaks)
  
  
  Machine Learning Enthusiast having a decent knowledge of Back-end Development. 
  <br><br>
  
  
  - Note: This Portofolio is under development. Hence, some links might not work. 
  Sorry for the inconvenience.
  
   <br><br>
  
  <a href="https://www.linkedin.com/in/kalpan-tumdi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
